#!/usr/bin/env node
/**
 * Cross-reference src/icons/figma-icons.json against Material Symbols' own
 * canonical manifest and produce:
 *
 *  - src/icons/material/iconNames.generated.ts — the `IconName` union (source
 *    of truth: Material's icon-index.json, NOT Figma — see generate-icon-names.mjs)
 *  - src/icons/manifest.json — Figma name → canonical IconName + filled flag,
 *    for design-tool tooling only (Figma→Cube name lookup). This is NOT where
 *    `IconName` comes from; it just maps Figma's design-tool names onto it.
 *  - src/icons/custom/pending.json — Figma icons with no Material match.
 *
 * Naming rules (unchanged from the old SVG-export pipeline):
 * - Figma kebab/snake/spaces → Material slug (kebab-case)
 * - `-fill` / `-filled` suffix → same glyph, `filled: true` (fill is now a
 *   render-time axis, not a separate glyph/export)
 * - src/icons/material/overrides.json → manual Figma → Material slug fixes
 *
 *   npm run icons:sync
 */
import fs from "node:fs";
import path from "node:path";
import {
  parseFigmaIconName,
  resolveCanonicalIconName,
  resolveMaterialSlug,
} from "./lib/icon-naming.mjs";
import { loadCanonicalIconNames } from "./generate-icon-names.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const REGISTRY_FILE = path.join(ROOT, "src/icons/figma-icons.json");
const OVERRIDES_FILE = path.join(ROOT, "src/icons/material/overrides.json");
const MANIFEST_FILE = path.join(ROOT, "src/icons/manifest.json");
const PENDING_FILE = path.join(ROOT, "src/icons/custom/pending.json");
const ICON_NAMES_FILE = path.join(ROOT, "src/icons/material/iconNames.generated.ts");

function loadJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function resolveIcon(figmaEntry, overrides, canonicalNames) {
  const { base, filled, figmaName } = parseFigmaIconName(figmaEntry.figmaName);
  const slug = resolveMaterialSlug(base, overrides);
  const name = resolveCanonicalIconName(slug, canonicalNames);

  if (!name) {
    return {
      ok: false,
      figmaName,
      slug,
      reason: "not-in-material-manifest",
    };
  }

  return {
    ok: true,
    figmaName,
    category: figmaEntry.category ?? "Uncategorized",
    slug,
    filled,
    name,
  };
}

function generateManifest(resolvedIcons) {
  const manifest = {};

  for (const icon of resolvedIcons) {
    manifest[icon.figmaName] = {
      name: icon.name,
      category: icon.category,
      filled: icon.filled,
    };
  }

  return manifest;
}

function generateIconNamesFile(names) {
  const lines = [
    "/**",
    " * AUTO-GENERATED by `npm run icons:sync` (scripts/generate-icon-names.mjs) — do not edit by hand.",
    " *",
    " * Canonical icon name set, sourced directly from Material Symbols' own",
    " * manifest (`@material-symbols-svg/react/dist/metadata/icon-index.json`),",
    " * not from Figma. Names are the underscore_case `name` field from that",
    " * manifest (e.g. `account_circle`) — this IS the glyph's font ligature text,",
    " * which `materialSymbolsIconLibrary` relies on directly.",
    " *",
    ` * ${names.length} names.`,
    " */",
    "export type IconName =",
    ...names.map((name) => `  | "${name}"`),
    ";",
    "",
    "/** Runtime membership check / iteration — same set as the `IconName` type. */",
    "export const ICON_NAMES: readonly IconName[] = [",
    ...names.map((name) => `  "${name}",`),
    "];",
    "",
    "const ICON_NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES);",
    "",
    "export function isIconName(value: string): value is IconName {",
    "  return ICON_NAME_SET.has(value);",
    "}",
    "",
  ];
  return lines.join("\n");
}

function main() {
  if (!fs.existsSync(REGISTRY_FILE)) {
    console.error(`Missing ${path.relative(ROOT, REGISTRY_FILE)} — run npm run icons:extract first.`);
    process.exit(1);
  }

  // 1. Refresh the canonical IconName union from Material's own manifest.
  const canonicalNameList = loadCanonicalIconNames();
  const canonicalNames = new Set(canonicalNameList);
  fs.writeFileSync(ICON_NAMES_FILE, generateIconNamesFile(canonicalNameList));

  // 2. Cross-reference Figma's design-tool names against that canonical set.
  const registry = loadJson(REGISTRY_FILE);
  const overrides = loadJson(OVERRIDES_FILE);

  const resolved = [];
  const pending = [];

  for (const entry of registry.icons ?? []) {
    const result = resolveIcon(entry, overrides, canonicalNames);
    if (result.ok) {
      resolved.push(result);
    } else {
      pending.push({
        ...result,
        category: entry.category ?? "Uncategorized",
      });
    }
  }

  resolved.sort((a, b) => a.figmaName.localeCompare(b.figmaName));

  fs.writeFileSync(MANIFEST_FILE, `${JSON.stringify(generateManifest(resolved), null, 2)}\n`);

  fs.mkdirSync(path.dirname(PENDING_FILE), { recursive: true });
  fs.writeFileSync(
    PENDING_FILE,
    `${JSON.stringify(
      {
        note: "Figma icons with no match in Material Symbols' own manifest — implement under src/icons/custom/",
        icons: pending.sort((a, b) => a.figmaName.localeCompare(b.figmaName)),
      },
      null,
      2
    )}\n`
  );

  console.log(`Generated ${canonicalNameList.length} canonical icon names`);
  console.log(`  → ${path.relative(ROOT, ICON_NAMES_FILE)}`);
  console.log(`Cross-referenced ${resolved.length} Figma icons against the Material manifest`);
  console.log(`  → ${path.relative(ROOT, MANIFEST_FILE)}`);

  if (pending.length) {
    console.warn(`\n${pending.length} Figma icons need custom SVG or overrides:`);
    for (const item of pending.slice(0, 15)) {
      console.warn(`  - ${item.figmaName} → ${item.slug} (${item.reason})`);
    }
    if (pending.length > 15) {
      console.warn(`  … and ${pending.length - 15} more (see ${path.relative(ROOT, PENDING_FILE)})`);
    }
  }
}

main();
