#!/usr/bin/env node
/**
 * Generate Material icon wrappers from src/icons/figma-icons.json.
 *
 * Naming rules:
 * - Figma kebab/snake/spaces → Material slug (kebab-case path)
 * - `-fill` / `-filled` suffix → Material `*Fill` export from same slug
 * - src/icons/material/overrides.json → manual Figma → Material slug fixes
 *
 *   npm run icons:sync
 */
import fs from "node:fs";
import path from "node:path";
import {
  cubeExportNameFromFigma,
  parseFigmaIconName,
  readMaterialSymbolExports,
  resolveMaterialSlug,
} from "./lib/icon-naming.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const REGISTRY_FILE = path.join(ROOT, "src/icons/figma-icons.json");
const OVERRIDES_FILE = path.join(ROOT, "src/icons/material/overrides.json");
const MATERIAL_ICONS_DIR = path.join(
  ROOT,
  "node_modules/@material-symbols-svg/react/dist/rounded/icons"
);
const SOURCE_FILE = path.join(ROOT, "src/icons/material/source.ts");
const INDEX_FILE = path.join(ROOT, "src/icons/material/index.ts");
const MANIFEST_FILE = path.join(ROOT, "src/icons/manifest.json");
const PENDING_FILE = path.join(ROOT, "src/icons/custom/pending.json");
const ALIASES_FILE = path.join(ROOT, "src/icons/material/aliases.json");

function loadJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function resolveIcon(figmaEntry, overrides) {
  const { base, filled, figmaName } = parseFigmaIconName(figmaEntry.figmaName);
  const slug = resolveMaterialSlug(base, overrides);
  const material = readMaterialSymbolExports(slug, MATERIAL_ICONS_DIR);

  if (!material) {
    return {
      ok: false,
      figmaName,
      slug,
      reason: "material-slug-not-found",
    };
  }

  const materialSymbol = filled ? material.fill : material.outline;
  if (!materialSymbol) {
    return {
      ok: false,
      figmaName,
      slug,
      reason: filled ? "material-fill-not-found" : "material-outline-not-found",
    };
  }

  return {
    ok: true,
    figmaName,
    category: figmaEntry.category ?? "Uncategorized",
    slug,
    filled,
    materialSymbol,
    exportName: cubeExportNameFromFigma(base),
  };
}

function generateSource(resolvedIcons) {
  const bySlug = new Map();

  for (const icon of resolvedIcons) {
    if (!bySlug.has(icon.slug)) bySlug.set(icon.slug, new Set());
    bySlug.get(icon.slug).add(icon.materialSymbol);
  }

  const lines = [
    "/**",
    " * AUTO-GENERATED by `npm run icons:sync` — do not edit by hand.",
    " * Material Symbols Rounded (w400) imports only.",
    " */",
  ];

  for (const slug of [...bySlug.keys()].sort()) {
    const symbols = [...bySlug.get(slug)].sort();
    lines.push(
      `export { ${symbols.join(", ")} } from "@material-symbols-svg/react/rounded/${slug}";`
    );
  }

  lines.push("");
  return `${lines.join("\n")}`;
}

function generateIndex(resolvedIcons, aliases) {
  const imports = new Set();
  const exportByName = new Map();

  for (const icon of resolvedIcons) {
    imports.add(icon.materialSymbol);
    if (!exportByName.has(icon.exportName)) {
      exportByName.set(
        icon.exportName,
        `export const ${icon.exportName} = createMaterialIcon(${icon.materialSymbol});`
      );
    }
  }

  const aliasLines = [];
  for (const [alias, target] of Object.entries(aliases).sort(([a], [b]) => a.localeCompare(b))) {
    if (!exportByName.has(target)) {
      console.warn(`Alias ${alias} → ${target} skipped (target export missing)`);
      continue;
    }
    aliasLines.push(`export { ${target} as ${alias} };`);
  }

  const lines = [
    "/**",
    " * AUTO-GENERATED by `npm run icons:sync` — do not edit by hand.",
    " */",
    ...[...imports].sort().map((name) => `import { ${name} } from "./source";`),
    'import { createMaterialIcon } from "./createMaterialIcon";',
    "",
    "/** Material Symbols Rounded (w400) — sized by {@link Icon}, not by the glyph. */",
    ...[...exportByName.values()].sort(),
  ];

  if (aliasLines.length) {
    lines.push("", "/** Legacy / semantic aliases (see aliases.json). */", ...aliasLines);
  }

  lines.push("");
  return `${lines.join("\n")}`;
}

function generateManifest(resolvedIcons) {
  const manifest = {};

  for (const icon of resolvedIcons) {
    manifest[icon.figmaName] = {
      source: "material-rounded",
      export: icon.exportName,
      category: icon.category,
      style: "rounded",
      weight: 400,
      materialSlug: icon.slug,
      filled: icon.filled,
    };
  }

  return manifest;
}

function main() {
  if (!fs.existsSync(REGISTRY_FILE)) {
    console.error(`Missing ${path.relative(ROOT, REGISTRY_FILE)} — run npm run icons:extract first.`);
    process.exit(1);
  }

  const registry = loadJson(REGISTRY_FILE);
  const overrides = loadJson(OVERRIDES_FILE);
  const aliases = fs.existsSync(ALIASES_FILE) ? loadJson(ALIASES_FILE) : {};

  const resolved = [];
  const pending = [];

  for (const entry of registry.icons ?? []) {
    const result = resolveIcon(entry, overrides);
    if (result.ok) {
      resolved.push(result);
    } else {
      pending.push({
        ...result,
        category: entry.category ?? "Uncategorized",
      });
    }
  }

  resolved.sort((a, b) => a.figmaName.localeCompare(b.figmaName));

  fs.writeFileSync(SOURCE_FILE, generateSource(resolved));
  fs.writeFileSync(INDEX_FILE, generateIndex(resolved, aliases));
  fs.writeFileSync(MANIFEST_FILE, `${JSON.stringify(generateManifest(resolved), null, 2)}\n`);

  fs.mkdirSync(path.dirname(PENDING_FILE), { recursive: true });
  fs.writeFileSync(
    PENDING_FILE,
    `${JSON.stringify(
      {
        note: "Figma icons with no Material Symbols Rounded match — implement under src/icons/custom/",
        icons: pending.sort((a, b) => a.figmaName.localeCompare(b.figmaName)),
      },
      null,
      2
    )}\n`
  );

  console.log(`Synced ${resolved.length} Material icons`);
  console.log(`  → ${path.relative(ROOT, SOURCE_FILE)}`);
  console.log(`  → ${path.relative(ROOT, INDEX_FILE)}`);
  console.log(`  → ${path.relative(ROOT, MANIFEST_FILE)}`);

  if (pending.length) {
    console.warn(`\n${pending.length} icons need custom SVG or overrides:`);
    for (const item of pending.slice(0, 15)) {
      console.warn(`  - ${item.figmaName} → ${item.slug} (${item.reason})`);
    }
    if (pending.length > 15) {
      console.warn(`  … and ${pending.length - 15} more (see ${path.relative(ROOT, PENDING_FILE)})`);
    }
  }
}

main();
