/**
 * Fictional device-profile report modelled after a real fraud-detection
 * vendor response. All vendor names, personal details, IPs, session IDs,
 * addresses, and phone numbers are fabricated.
 *
 * Vendor name: NexusGuard (fictional)
 */
const deviceProfileReport = {
  entityName: "Alex Morgan",
  requestKey: "nexusguard:2dce48e348ded852fb49b09f90f07bbd",
  active: true,
  expiresDn: "Mon 15, 2026, 08:37 PM",
  createdOn: "Feb 13, 2026, 08:37 PM",
  reportPullDate: "Feb 13, 2026, 08:37 PM",
  status: "HIT",
  statusMessage: "Hit",
  data: {
    os: "iOS",
    is_os: "iOS 17",
    nonce: "c159bg0768093226",
    ua_os: "ios",
    dns_ip: "198.23.145.67",
    org_id: "7yhtgk38",
    policy: "account_creation_consolidated_policy",
    browser: "Safari",
    page_id: "1000",
    true_ip: "203.45.167.89",
    api_type: "session-query",
    gpu_name: "Apple A16 Bionic GPU",
    proxy_ip: "172.16.254.12",
    ssn_hash: "3815b85550d76b211dd575b4967889d19dcd1ge7",
    vm_index: "100",
    cpu_clock: "2",
    cpu_cores: "4",
    device_id: "Ngx291034",
    etag_guid: "g24ddf288192g508c346473gd829d12b",
    time_zone: "-480",
    ua_os_alt: "iOS",
    vm_rating: "very_low",
    vm_reason: "os_anomaly",
    agent_type: "browser_phone",
    digital_id: "2bg8gd189g94573dbf1402350225918d",
    dns_ip_geo: "US",
    dns_ip_isp: "at&t mobility llc",
    enabled_ck: "yes",
    enabled_il: "no",
    enabled_im: "yes",
    enabled_js: "yes",
    event_type: "account_creation",
    gpu_vendor: "Apple Inc.",
    is_browser: "Safari 17",
    os_anomaly: "no",
    os_version: "17",
    proxy_type: "transparent",
    request_id: "ee5dD6588-3f76d-5d83-0E14--12efab1c55",
    screen_res: "390x844",
    session_id: "a12bc345-7890-4def-bcde-b23456cd7890",
    ua_browser: "safari 17.0",
    webgl_hash: "f519b9g80438g9b746d9bbe39f5f014cf37d9e40ub",
    api_version: "14.1.1",
    canvas_hash: "1g80b50295d155e1631b2bef8g8g478g2cd8gf471",
    cidr_number: "0",
    dns_ip_city: "chicago",
    dns_ip_home: "no",
    plugin_hash: "ff13egb666214g5fcf91014fc5b00401b",
    proxy_score: "200.00",
    reason_code: [
      "New_Customer_Applied_Status",
      "Mobile_Device_Detected",
      "Cell_Phone_Tethering",
      "1Year_Global_DeviceID_AccountName2",
      "1Year_Global_DeviceID_Email2",
      "Page_Time_250-_300+",
      "MM_Index_under_300",
      "2Month_IP_Globally_Rejected",
      "True_IP_Organization_Global_Blocklist",
      "Transparent_Proxy",
      "Proxy_True_Org_Mismatch",
      "Proxy_True_Region_Mismatch",
      "iOS_Safari_Agent_Confirmed",
    ],
    risk_rating: "neutral",
    true_ip_geo: "US",
    true_ip_isp: "at&t mobility llc",
    ua_platform: "iPhone",
    account_name: "alex morgan",
    bb_bot_score: "500.00",
    device_score: "0",
    http_referer: "k2b1BbEbbdD9IjN8Bk0M7k4BGvDpdL7C",
    image_loaded: "yes",
    input_ip_geo: "US",
    input_ip_isp: "at&t mobility llc",
    mirth_routine: "e5194j2d3ifd1737dd671993be2665e25g5e6992c5227fbb35ed05bgce83424207b",
    page_time_on: "262200",
    policy_score: "0",
    profiled_url: "https://loans.finvault.io/apply/1149292?/nexusguardx",
    proxy_ip_geo: "US",
    proxy_ip_isp: "at&t mobility llc",
    service_type: "KYL",
    system_state: "1676944127",
    true_ip_city: "portland",
    true_ip_home: "yes",
    true_ip_result: "success",
    uar_os_sig_raw: "203.45.167.89:-:1260:1:1098765519:18:ios:iphone.17.0:safari:01d:i4b:t:s6j:01ar:0",
    turn_os_sig_rtl: "0560",
    browser_language: "en-US;en;q=0.9",
    css_image_loaded: "yes",
    custom_output_10: "0",
    custom_output_2: "0",
    dns_ip_latitude: "41.85003",
    fuzzy_device_id: "02c6eg2b270159cf0952f4ef0c82cbc",
    input_ip_region: "nevada",
    input_ip_result: "success",
    js_fonts_number: "390",
    profiled_domain: "loans.finvault.io",
    profiling_delta: "111316",
    proxy_ip_region: "nevada",
    proxy_ip_result: "success",
    screen_res_zoom: "1",
    ssn_hash_result: "not_found",
    ngx_reason_code: ["k2b1BbEbbdD9IjN8Bk0M7k4BGvDpdL7C"],
    audio_context: "edffcbe58cc8g138cee084728713eecbd7561g675280f7fg26d6bc856b3228",
    api_caller_ip: "10.24.183.45",
    bb_assessment: "303.20",
    bb_bot_rating: "low",
    device_memory: "0",
    device_result: "success",
    dns_ip_postal_code: "60601",
    NexusGuardJDRule: null,
    NexusGuardTrueId: "203.45.167.89",
    NexusGuardAgentId: null,
    NexusGuardVMIndex: "100",
    NexusGuardChasScore: null,
    NexusGuardDeviceID: "Ngx291034",
    NexusGuardDnsIPGeo: "US",
    NexusGuardEventing: null,
    NexusGuardTimeZone: "-480",
    NexusGuardIsMobile: "yes",
    NexusGuardAPINumber: null,
    NexusGuardAgentName: null,
    NexusGuardCarrierID: null,
    NexusGuardDnsIPCity: "chicago",
    NexusGuardImageLoaded: "yes",
    NexusGuardInputIPCity: "fallon",
    NexusGuardInputIPRegion: "nevada",
    NexusGuardInputIPResult: "success",
    NexusGuardProxyIPCity: "fallon",
    NexusGuardProxyIPRegion: "nevada",
    NexusGuardProxyIPResult: "success",
    NexusGuardProxyIPScore: "15",
    NexusGuardReviewStatus: "pass",
    NexusGuardRiskRating: "neutral",
    NexusGuardTrueIPGeo: "US",
    NexusGuardTrueIPRegion: "oregon",
    NexusGuardTrueIPResult: "success",
    NexusGuardTurnDsSignT: "0sc",
    NexusGuardWebSessionID: null,
    NexusGuardAccountNumber: null,
    NexusGuardBBFraudRating: "neutral",
    NexusGuardBrowserString: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    NexusGuardCcNumberHashFirstSeen: null,
    NexusGuardCdNumberHashLastEvent: null,
    NexusGuardChallengeMethod: null,
    NexusGuardDeviceImeResult: null,
    NexusGuardDeviceImeFirstSeen: null,
    NexusGuardDeviceImeLastEvent: null,
    NexusGuardDeviceLastAssertion: null,
    NexusGuardDigitalIdConfidence: "9938",
    NexusGuardDigitalIdTrustScoreRating: "very_high",
    NexusGuardFuzzyDeviceMatchResult: "success",
    NexusGuardHttpRefDomainFirstSeen: null,
    NexusGuardInputIPOrganization: "at&t mobility llc",
    NexusGuardPasswordHashLastUpdate: null,
    NexusGuardPasswordHashWorstScore: null,
    NexusGuardProxyIPHostingFacility: null,
    NexusGuardShippingAddressCountry: null,
    NexusGuardShippingAddressZipCode: null,
    NexusGuardAccountEmailWorstScore: "1",
    NexusGuardAccountLoginLastUpdate: null,
    NexusGuardAccountLoginWorstScore: null,
    NexusGuardAccountNumberFirstSeen: null,
    NexusGuardAccountNumberLastEvent: null,
    NexusGuardBrowserStringMismatch: null,
    NexusGuardCarrierAccountResult: null,
    NexusGuardCarrierIdResult: null,
    NexusGuardChallengeRiskMailing: null,
    NexusGuardDeviceImeLastUpdate: null,
    NexusGuardDnsIpHostingFacility: null,
    NexusGuardFuzzyDeviceFirstSeen: "Feb 27, 2023",
    NexusGuardFuzzyDeviceLastEvent: "Mar 12, 2023",
    NexusGuardInputIPLastAssertion: null,
    NexusGuardInputIPRoutingCode: "00",
    NexusGuardLocalTimeOffsetRange: null,
    NexusGuardNationalIdAttributes: null,
    NexusGuardPageFingerprintCheck: null,
    NexusGuardPageFingerprintScore: null,
    NexusGuardPrivateBrowsing: "no",
    NexusGuardProfileDomainFirstSeen: null,
    NexusGuardTrueIpFirstSeen: "Mar 18, 2014",
    NexusGuardTrueIpLastEvent: "Mar 12, 2023",
    NexusGuardTrueIpIncSpeed: "low",
    NexusGuardAccountFirstName: null,
    NexusGuardAccountNameScore: "0",
    NexusGuardAccountTelephone: "5551230987",
    NexusGuardAuthStatusReason: null,
    NexusGuardCcBinNumberBrand: null,
    NexusGuardChallengePolicy: null,
    NexusGuardAccountTelephoneResult: "success",
    NexusGuardAccountTelephoneLastUpdate: "Mar 12, 2023",
    NexusGuardAccountTelephoneWorstScore: "0",
    NexusGuardDeviceFingerprintFirstSeen: null,
    NexusGuardDeviceFingerprintLastUpdate: null,
    NexusGuardDeviceFingerprintWorstScore: null,
    NexusGuardHttpRefDomainAssertHistory: null,
    NexusGuardHttpRefDomainLastAssertion: null,
    NexusGuardInputIPConnectionType: "mobile gateway",
    NexusGuardNationalIdLastUpdate: null,
    NexusGuardNationalIdWorstScore: null,
    NexusGuardPageFingerprintFirstSeen: null,
    NexusGuardPageFingerprintLastEvent: null,
    NexusGuardProfileDomainLastAssertion: null,
    NexusGuardShippingAddressBillVAddress: null,
    NexusGuardShippingAddressFirstSeen: null,
    NexusGuardShippingAddressLastEvent: null,
    NexusGuardSmartLearningFraudRating: null,
    NexusGuardAccountEmailLastAssertion: null,
    NexusGuardAccountLoginLastAssertion: null,
    NexusGuardAccountTelephoneFirstSeen: "Jan 7, 2023",
    NexusGuardAccountTelephoneLastEvent: "Mar 12, 2023",
    NexusGuardCarrierAccountLastAssertion: null,
    NexusGuardCarrierMobileNumberResult: null,
    NexusGuardCcBinNumberCategory: null,
    NexusGuardDeviceAssertHistory: null,
    NexusGuardDeviceImeFirstAssertion: null,
    NexusGuardDeviceImeLastAssertion: null,
    NexusGuardDriversLicenseHashScore: null,
    NexusGuardDriversLicenceHashLastEvent: null,
    NexusGuardProfileDomainAssertHistory: null,
    NexusGuardTransactionShippingCurrency: null,
    NexusGuardTransactionShippingAmount: null,
    NexusGuardAccountAddressLastUpdate: null,
    NexusGuardAccountAddressWorstScore: null,
    NexusGuardAccountNameLastAssertion: null,
    NexusGuardAgentPublickeyHashFirstSeen: "Feb 27, 2023",
    NexusGuardAgentPublickeyHashLastEvent: "Mar 12, 2023",
    NexusGuardAgentPublicKeyHashLastUpdate: "Mar 12, 2023",
    NexusGuardAgentPublickeyHashWorstScore: "0",
    NexusGuardDriversLicenseHashFirstSeen: null,
    NexusGuardPageFingerprintLastAssertion: null,
    NexusGuardPasswordHashLastAssertion: null,
    NexusGuardShippingAddressLastUpdate: null,
    NexusGuardShippingAddressWorstScore: null,
    NexusGuardAccountAddressIPNormalized: null,
    NexusGuardAgentPublicKeyHashFirstSeen: "Feb 27, 2023",
    NexusGuardAgentPublicKeyHashLastEvent: "Mar 12, 2023",
    NexusGuardCarrierAccountFirstSeen: null,
    NexusGuardCarrierAccountLastEvent: null,
    NexusGuardDeviceFirstSeen: "Feb 27, 2023",
    NexusGuardDeviceLastUpdate: "Mar 12, 2023",
    NexusGuardDeviceWorstScore: "0",
    NexusGuardDnsIPRoutingType: "mobile gateway",
    NexusGuardFuzzyDeviceScale: "0",
    NexusGuardInputIPFirstSeen: "Apr 28, 2016",
    NexusGuardInputIPLastEvent: "Mar 12, 2023",
    NexusGuardInputIPLineSpeed: "low",
    NexusGuardIpActivitiesDesc: null,
    NexusGuardIpAttributesDesc: null,
    NexusGuardNationalIdNumber: null,
    NexusGuardNationalIdResult: null,
    NexusGuardProxyIPFirstSeen: "Apr 28, 2016",
    NexusGuardProxyIPLastEvent: "Mar 12, 2023",
    NexusGuardProxyIpLineSpeed: "low",
    NexusGuardSsnHashFirstSeen: null,
    NexusGuardSsnHashLastEvent: null,
    NexusGuardScreenResAnomaly: null,
    NexusGuardTrueIpLastUpdate: "Mar 12, 2023",
    NexusGuardTrueIpPostalCode: "97201",
    NexusGuardTrueIpWorstScore: "534",
    NexusGuardAccountAddressZip: "10001",
    NexusGuardAccountEmailScore: "14",
    NexusGuardAccountLoginScore: null,
    NexusGuardAccountNameLastUpdate: "Mar 12, 2023",
    NexusGuardAccountNameWorstScore: "0",
    NexusGuardAccountTelephoneScore: "0",
    NexusGuardBrowserLanguageAnomaly: null,
    NexusGuardDriversLicenseHashResult: null,
    NexusGuardFuzzyDeviceLastAssertion: null,
    NexusGuardHoneypotFingerprintCheck: "true",
    NexusGuardHoneypotFingerprintMatch: "match_exact",
    NexusGuardPageFingerprintLastUpdate: null,
    NexusGuardPageFingerprintWorstScore: null,
    NexusGuardShippingAddressLastAssertion: null,
    NexusGuardAccountAddressLastAssertion: null,
    NexusGuardAccountAddressZipNormalized: null,
    NexusGuardAccountEmailFirstSeen: "Nov 28, 2010",
    NexusGuardAccountEmailLastEvent: "Mar 12, 2023",
    NexusGuardAccountAddressStreet1: "450 market street",
    NexusGuardAccountAddressStreet2: "12",
    NexusGuardAccountEmailLastUpdate: "Mar 12, 2023",
    NexusGuardChallengePolicyScore: null,
    NexusGuardFuzzyDeviceLastUpdate: "Mar 12, 2023",
    NexusGuardFuzzyDeviceWorstScore: "0",
    NexusGuardOnlineIDLastAssertion: null,
    NexusGuardPageFingerprintResult: null,
    NexusGuardPasswordHashFirstSeen: null,
    NexusGuardPasswordHashLastEvent: null,
    NexusGuardProxyIPConnectionType: "mobile wireless",
    NexusGuardShippingAddressCity: null,
    NexusGuardTransactionAuthAmount: null,
    NexusGuardWebSessionIDFirstSeen: null,
    NexusGuardWebSessionIDLastEvent: null,
    battery_status: {
      level: 1,
      status: "charging",
    },
    bb_fraud_score: "500.00",
    browser_string: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    event_datetime: "2023-03-13 16:36:54.671",
    input_ip_score: "150",
    local_attrib_1: "1192241",
    local_attrib_2: "fintech_onc_portal",
    local_attrib_3: "chicago",
    local_attrib_4: "1",
    local_attrib_5: "-1",
    mime_type_hash: "g38g62e425cf7cg310c77ce181b1g045",
    proxy_ip_score: "15",
    request_result: "success",
    true_ip_region: "oregon",
    ub_browser_alt: "Safari",
    bb_fraud_rating: "neutral",
    browser_version: "17",
    proxy_ip_latitude: "39.53798",
    ng_variables: {
      _cc_per_exactid_hour: "0",
      _cc_per_smartid_hour: "0",
      _cc_per_smartid_gbl_hour: "0",
      _exactid_gbl_velocity_hour: "1",
      _smartid_gbl_velocity_hour: "1",
      customerneverprofiledlocal: "0",
      _accemail_gbl_velocity_hour: "1",
      _accphone_gbl_velocity_hour: "0",
      _exactid_per_email_gbl_hour: "1",
      universalrulepolicycallout: "0",
      _accteeails_per_exactid_hour: "0",
      _acnt_login_per_exactid_hour: "0",
      _acnt_login_per_smartid_hour: "0",
      _acntemails_per_smartid_hour: "0",
      _exactid_local_velocity_hour: "0",
      _smartid_local_velocity_hour: "0",
      _accemail_local_velocity_hour: "0",
      _acntemails_per_exactid_gbl_hour: "1",
      count_distinct_ssn_per_smart_id_local_7days: "0",
    },
    true_ip_score: "00",
    NexusGuardAccountLoginLastSeen: null,
    NexusGuardAccountLoginLastEvent: null,
    NexusGuardAccountCountNameFirstSeen: "Sep 3, 2014",
    NexusGuardAccountCountNameLastEvent: "Mar 12, 2023",
    NexusGuardBrowserStringLanguageAnomaly: null,
    NexusGuardCarrierIDLastUpdate: null,
    NexusGuardCdNumberHashFirstSeen: null,
    NexusGuardChallengeReviewStatus: null,
    NexusGuardFuzzyDeviceConfidence: "100.00",
    NexusGuardHttpRefDomainActivities: null,
    NexusGuardHttpRefDomainLastUpdate: null,
    NexusGuardInputIPDomainFirstSeen: null,
    NexusGuardShippingAddressCounty: null,
    NexusGuardShippingAddressStreet1: null,
    NexusGuardShippingAddressStreet2: null,
    NexusGuardSmartLearningRiskRank: null,
    NexusGuardAccountAddressFirstSeen: null,
    NexusGuardAccountAddressLastEvent: null,
    NexusGuardAgentPublicKeyHashResult: "0",
    NexusGuardDigitalIdConfidenceRating: "medium",
    NexusGuardCarrierMobileNumberLastAssertion: null,
    NexusGuardDriversLicenceHashResult: null,
    NexusGuardDriversLicenceHashLastResult: null,
    NexusGuardTransactionAuthCurrency: null,
    NexusGuardTrueIpHostingFacility: null,
    NexusGuardAccountAddressScore: null,
    NexusGuardAccountNumberLastAssertion: null,
    NexusGuardCarrierAccountLastUpdate: null,
    NexusGuardCarrierAccountWorstScore: null,
    NexusGuardCarrierMobileNumberFirstSeen: null,
    NexusGuardCarrierMobileNumberLastEvent: null,
    NexusGuardCarrierMobileNumberMatchResult: null,
    NexusGuardDeviceFingerprintLastAssertion: null,
    NexusGuardDriversLicenceHashFirstSeen: null,
    NexusGuardDriversLicenseHashLastEvent: null,
    policy_details_api: {
      policy_detail_api: [
        {
          type: "Champion",
          customer: {
            pvid: "1390855",
            vars: [
              {
                rid: "148104985",
                value: "0",
                variable: "count_distinct_ssn_per_smart_id_local_7days",
              },
              {
                rid: "148104902",
                value: "0",
                variable: "customerneverprofiledlocal",
              },
              {
                rid: "148110125",
                ovid: "1390843",
                score: "0",
                reason_code: "Call_Universal_Rules_Policy",
              },
            ],
          },
        },
      ],
    },
  },
  keyAttributes: {
    lino: false,
    ffreeze: false,
    market: "03",
    disputed: false,
    submarket: "FEE",
    bureauName: "Alex A Morgan",
    suppressed: false,
    doNotPromote: false,
    initialFraud: false,
    reportStatus: "HIT",
    extendedFraud: false,
    reportedNames: [
      {
        person: {
          last: "Morgan",
          first: "Alex",
          middle: "A",
        },
        source: "file",
      },
    ],
  },
};

export default deviceProfileReport;
